name: Release for Android

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Flutter
        run: |
          java -version
          git submodule update --init --recursive

      - name: Prepare Flutter Dependencies
        run: |
          .flutter/bin/flutter config --no-analytics
          .flutter/bin/flutter pub get

      # 【已删除签名步骤，交由 build.gradle 自动降级为 debug 签名】

      - name: Build APKs
        # 移除了单平台限制，恢复你最初需要的三架构分离
        run: |
          .flutter/bin/flutter build apk --release --split-per-abi

      - name: Upload All APKs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apks
          # 将三个包全部打包上传
          path: build/app/outputs/flutter-apk/*.apk
